# This workflow will install Python dependencies, run tests and lint for Python scripts
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Covid-19 DP submission CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        vcf-validator-version: [0.9.4]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py install
        # Install Nextflow
        mkdir /tmp/nextflow && cd /tmp/nextflow
        wget -qO- get.nextflow.io | bash
        echo "/tmp/nextflow" >> $GITHUB_PATH
    - name: Set up VCF validator and assembly checker
      run: |
        sudo bash -c "cd /usr/bin && wget https://github.com/EBIvariation/vcf-validator/releases/download/v${{ matrix.vcf-validator-version }}/vcf_validator_linux && chmod 755 vcf_validator_linux"

